# Site settings
title: RAOYI
subtitle: Debris collection
description: RaoYi's page
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://raoyi.net" # 你的网址
domain: "raoyi.net" # 你的域名
page_no_title: "No title" # 文章无标题时默认显示内容
beian: # "备案号"
email: hi@raoyi.net

# Build settings
permalink: /:year/:month/:day/:title/
exclude: ["README.md", "changelog.md", "server", "tools", "Pipfile"]
plugins: [jekyll-paginate]
auto: true
markdown: redcarpet
redcarpet:
    extensions: ["fenced_code_blocks",
                 "tables",
                 "highlight",
                 "strikethrough",
                 "no_intra_emphasis",
                 "with_toc_data"]

# Pageinate settings
page_size: 10 # 分页大小
paginate: 10
paginate_path: ":num"

# Search settings
baidu_search: true
google_search: # true

# Menu settings
menu:
  - page: 首页
    directory: .
    icon: icon-home
  - page: 归档
    directory: archives/
    icon: icon-archive
#  - page: 关于
#    directory: about/
#    icon: icon-about
  - page: 链接
    directory: links/
    icon: icon-history
  - page: 订阅
    directory: feed.xml
    icon: icon-rss

# Link settings
#links: # 友情链接
#  - title: site-name1
#    url: http://www.example1.com/
#  - title: site-name2
#    url: http://www.example2.com/
#  - title: site-name3
#    url: http://www.example3.com/

# Code hub settings
codehub: # 代码仓库
  - title: Github
    url: https://github.com/raoyi
  - title: Gitee
    url: https://gitee.com/raoyi
